### ISSUE TITLE
Vram requirements

### ISSUE THREAD

**Issue by camjac251** [Maclory/Deep-Iterative-Collaboration#1]
Hi there. I wanted to try this project with its amazing examples of face upscaling. I'm on a P5000 with roughly 13.3GB of usable VRAM in Windows 10 but I've gotten out of memory errors in trying to upscale my own image. I even cropped in to the face as far as I could but it always fails.

I'm on Python 3.8 with the latest versions of all of the requirements and cudatoolkit 10,1 (from conda)

These are some of the messages I've gotten back
```
RuntimeError: CUDA out of memory. Tried to allocate 5.13 GiB (GPU 0; 16.00 GiB total capacity; 5.34 GiB already allocated; 4.59 GiB free; 8.47 GiB reserved in total by PyTorch)
```
```
RuntimeError: CUDA out of memory. Tried to allocate 2.95 GiB (GPU 0; 16.00 GiB total capacity; 12.10 GiB already allocated; 962.25 MiB free; 12.12 GiB reserved in total by PyTorch)
```

**Comment by Steve-Tod** [comment]
Hi, are you running the test or training?

**Comment by camjac251** [comment]
I'm attempting to test based on the pretrained models

**Comment by Steve-Tod** [comment]
We did our test with 16X16 input images and batchsize 1 and it takes only 1373MB GPU memory. Maybe you are using too large image or your GPU memory is already used up?

**Comment by camjac251** [comment]
I was using images that were about 100x100 pixels. I attempted to downscale the image to 16x16 and use that as an input but the result didn't look that good.

**Comment by Steve-Tod** [comment]
The unsatisfactory results might be caused by different preprocessing. In our experiments, images are cropped in a uniform way based on the detected face landmarks.

**Comment by Glorainow** [comment]
> The unsatisfactory results might be caused by different preprocessing. In our experiments, images are cropped in a uniform way based on the detected face landmarks.

Hi, I wonder what kind of preprocessing method is applied? Does different cropping method lead to different results?

**Comment by Steve-Tod** [comment]
In our experiments, we crop the images based on landmark annotations following previous works. First, we find a rectangular bounding box that can cover the landmarks tightly. Then we crop this bounding box to a square box with length equal to the short side of the rectangular box centered at the same point. Finally, we crop the image with the square box expanded by a scale factor of 1.3 and resize it to 128X128 by bicubic.
I think a large difference in cropping strategies might affect the performance while small differences might have sight effects since the alignment network can help localize the faces.
