### ISSUE TITLE
Size of tensor A must match size of tensor B

### ISSUE THREAD

**Issue by ZeeRizvee** [Maclory/Deep-Iterative-Collaboration#18]
Dear Author,
Reference to my previous opened issue #16, can you kindly guide me further over what exactly is causing this error? The previous issue was closed before my problem being solved. I am still stuck at the same error. I am working with pre trained weights of CelebA dataset, however the issue exists on with pre trained weights on Helen dataset as well. I am working with the DICGAN model. Some specific resolutions that the code successfully works on are 24x24, 32x32, 40x40 and 56x56. The code fails with this error on almost all resolutions between these, as trial and error has showed.

**Comment by Steve-Tod** [comment]
Hi, thank you for your interest in our work. I think the point here is that **the input width and height should be a multiple of 8**. Because if the upscale factor is 8, then there are convolutional layers with stride 8(you can check [here](https://github.com/Maclory/Deep-Iterative-Collaboration/blob/5d3c271740ca3b9278b7566ad8489aaa7d5afbc0/code/networks/srfbn_arch.py#L21)), which means if the input size is not a multiple of 8, it's not divisible and output size is not exactly 1/8 of the input. Then after transposed convolutional layer(upsample) with stride 8, output size will not be the same as input size. This will lead to error in the later fusing operations.
My suggestion is that you can resize the input to size which is a multiple of 8.

**Comment by ZeeRizvee** [comment]
Yes that finally solves the issue! Thank you for the elaborate explanation as to what exactly was causing this issue. Its working perfectly now!
