### ISSUE TITLE
Question about the train.json

### ISSUE THREAD

**Issue by wcy-cs** [Maclory/Deep-Iterative-Collaboration#22]
Hi,thank you very much for your sharing the code!
I have some question about the parameter setting.
In train_CelebA, there is no "distort", while in the train_helen, the "distort" is [0.66, 1.33]. Why the difference occur here. In the paper, the LR and HR from both CelebA and Helen are 16X16 and 128x128.
I am looking forward to you answer. Thanks.

**Comment by Steve-Tod** [comment]
Hi, distort mean randomly change the ratio of height and width of the region to be cropped (like RandomResizedCrop). We only use it for Helen because there are only 2k images in Helen's training set. To avoid overfitting, we use "distort". However, there are enough images in CelebA so we don't need that.
