### ISSUE TITLE
questions about testing

### ISSUE THREAD

**Issue by Darrenxc** [Maclory/Deep-Iterative-Collaboration#4]
During testing, in my opinion, it will produce an 8x scale SR image w/o annotations (pkl files)?.
Can this model produce a face deblurred image without resolution changing? 
Due to this model based on 8x scale, how much memory is needed to upscale a 128x128 image?

**Comment by Maclory** [comment]
1. Yes, that's right. 
2. Since our model is trained for SR of 8x, it cannot deblur a face image without resolution changing. However, you can modify the network architecture by removing upscaling layers and train a new model for face deblurring. 
3. If the input is of 128x128, then the output will be of 1024x1024. It will cost a large amount of memory and the model of current version cannot handle such images.
